### ISSUE TITLE
Config and cache store subsystem

### ISSUE THREAD

**Issue by antonydevanchi** [HellsHamsters/datacat#8]
Required to store data on drive, because seems like runtime will have a many cache files and already need store cached recent and saved connections.

### About files place

According to agreements in Linux / OS X systems i planning store it in user's home folder e.g. `/home/username/.datacat`. For Windows system sounds like as good solution is store data to `\Users\username\.datacat`.

### Why not electron-xxx package for config/cache files?

It is my deep conviction that need control how is really works a mostly important subsystem in project and therefore a reliable way is not "Let's start require 3rd-party package and investigate how it works right after app was launched in release", but "implement exactly what you need as a simple and totally understandable part of project".

Also, any 3rd-party package will need support from time to time and nobody can guarantee that 3rd-party package maintainers will be enough involved in project for closing issues operatively.

### TO-DO

- [x] Simply way to get absolute path to currently user's home directory.
- [ ] Understandable API for manipulating files and data on Main and Renderer sides.
- [x] While first launch need create `.datacat` folder and default data stores files for minimum functionality: `config.json` and `connections.json`.

**Comment by antonydevanchi** [comment]
Config API added in @c35fcdc
